### ISSUE TITLE
US12 Plantear Historias de Usuarios (derivadas de los requerimientos) y Tareas dependientes de las US para incorporarlas en el repositorio remoto gitHub. (Issues y Milestones) - Tener en cuenta la redacción adecuada para las US y nomenclatura, ej “#US01 Como usuario quiero ingresar al carrito para poder comprar”

### ISSUE THREAD

**Issue by carlos-linero** [Proyectos-ISPC/proyecto-app-mobile#12]
- [x] #TK00 Definir tareas dentro de la Historia de Usuario.
- [x] #TK1 Una vez realizada la tarea #11 pasar los requerimientos a historias de usuario en el Project en Github.

**Comment by carlos-linero** [comment]
- [ ] #TK1 Una vez realizada la tarea #11 pasar los requerimientos a historias de usuario en el Project en Github.

**Comment by GiulianaDeEt** [comment]
Hecho y entregado.
